#ifdef UNIT_TEST_PROG
#ifndef TESTS_TIMEFRAME_TESTS_STREAM_OPERATORS_TEST_STREAM_OPERATORS_HPP_INCLUDED
#define TESTS_TIMEFRAME_TESTS_STREAM_OPERATORS_TEST_STREAM_OPERATORS_HPP_INCLUDED

namespace testing
{
    bool test_interval_streams();
    
}

#endif
#endif